### ISSUE TITLE
Reindex from a block height

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1095]
**Objective:**
Since we support historical data, similar as the database snapshot, which mean we could allow user to reindex to specific block height.

**Todo:**

- [ ] use flag `--reindex` = blockHeight
- [ ] validate reindexing blockHeight with metadata (lastProcessedHeight), update metadata once it successful rewinded
- [ ]  if POI is on, delete mmr to the height(leafIndex), also remove Poi records.
- [ ] Remove data in other tables
- [ ] put in a tx, if it failed to rewind we still have the original data.
